* [org-mode] PDF-Export-Variables                                  :noexport:
  [[https://github.com/vikasrawal/orgpaper/][orgpaper]] [[http://orgmode.org/manual/Export-settings.html][Org-Mode Export-Settings]] [[http://en.wikibooks.org/wiki/LaTeX/Print_version][nice LaTeX reference]]
** org-mode startup
#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: entitiespretty
*** Symbole
    [[http://orgmode.org/worg/org-symbols.html][verfügbare Symbols]]
** LaTeX Header
*** eigene Titlepage
    see [[http://orgmode.org/tmp/worg/org-tutorials/org-latex-export.html][11.2 Titles and Title Page Layout]]
,#+LATEX_HEADER: \input{mytitle}
*** Font
**** Arial
#+LATEX_HEADER: \renewcommand{\rmdefault}{phv} % Arial as Font!
**** libertine
,#+LATEX_HEADER: \usepackage{libertine}
**** garamond
,#+LaTeX_CLASS_OPTIONS: [garamond]
*** Zeilen-Abstand
,#+LATEX_HEADER: \usepackage{setspace}
,#+LATEX_HEADER: \onehalfspacing
*** language-specific [babel]
**** german
#+LANGUAGE:  de
#+LATEX_HEADER: \usepackage[ngerman]{babel}
**** neccessary
,#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage[T1]{fontenc} 
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
**** neo2 - uniinput
#+LATEX_HEADER: \usepackage{uniinput}
*** Links [hyperref]
**** remove boxes, use dark colored fonts to indicate links
,#+LATEX_HEADER: \usepackage{xcolor}
,#+LATEX_HEADER: \hypersetup{
,#+LATEX_HEADER:     colorlinks,
,#+LATEX_HEADER:     linkcolor={red!50!black},
,#+LATEX_HEADER:     citecolor={blue!50!black},
,#+LATEX_HEADER:     urlcolor={blue!80!black}
,#+LATEX_HEADER: }
**** green!
#+LATEX_HEADER: \usepackage{xcolor}% http://ctan.org/pkg/xcolor
#+LATEX_HEADER: \usepackage{hyperref}% http://ctan.org/pkg/hyperref
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:   colorlinks=true,
#+LATEX_HEADER:   linkcolor=blue!50!red,
#+LATEX_HEADER:   urlcolor=green!70!black
#+LATEX_HEADER: }
**** get rid of the red boxes drawn around links
,#+LATEX_HEADER: \usepackage{hyperref}  % 
,#+LATEX_HEADER: \hypersetup{
,#+LATEX_HEADER:     colorlinks,%
,#+LATEX_HEADER:     citecolor=black,%
,#+LATEX_HEADER:     filecolor=black,%
,#+LATEX_HEADER:     linkcolor=blue,%
,#+LATEX_HEADER:     urlcolor=black
,#+LATEX_HEADER: }
*** extra packages [graphicx]
,#+LATEX_HEADER: \usepackage{graphicx}
*** Seitenränder anpassen [geometry]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{left=1.2in,right=1.2in,top=1.2in,bottom=1.2in}

*** [todonotes]
,#+LaTeX_HEADER: \usepackage{todonotes}
**** vorher laden, falls mit optionen geladen werden soll
     - ifthen
     - xkeyval
     - xcolor
     - tikz
     - calc
     - graphicx
*** bibliograbhy [biblatex][csquotes]
,#+LATEX_HEADER: \usepackage["backend=bibtex, citestyle=authoryear-icomp, bibstyle=authoryear, hyperref=true, backref=true, maxcitenames=3, url=true, natbib=true"]{biblatex}
,#+LaTeX_HEADER: \usepackage[backend=biber]{biblatex}
,#+LaTeX_HEADER: \usepackage{csquotes}
,#+LaTeX_HEADER: \bibliography{./bibliography}
,#+LATEX_HEADER: \addbibresource{./bibliography}
,#+LaTeX_HEADER: \bibliography{references}
** Options
*** Inhaltsverzeichnis anpassen
#+OPTIONS: toc:2 H:3 num:2

*** Quotes
    Toggle smart quotes (org-export-with-smart-quotes).
#+OPTIONS: ':t

*** Tiefstellen
    Toggle TeX-like syntax for sub- and superscripts. If you write "^:{}",
    ‘a_{b}’ will be interpreted, but the simple ‘a_b’ will be left as it is
    (org-export-with-sub-superscripts).
#+OPTIONS: ^:nil

*** Tags exportieren?
#+OPTIONS: tags:n

** misc
#+TITLE: demo
#+DATE: \today
#+AUTHOR: Eduard Urfaust
#+EMAIL: Feder.Stahl@mode.org
