* [LaTeX]
** [Tikz]
*** Tikz picture - Grid - Draw on image
    [[http://tex.stackexchange.com/questions/9559/drawing-on-an-image-with-tikz][Stack Exchange]]
    #+BEGIN_SRC latex
      \begin{tikzpicture}
          \node[anchor=south west,inner sep=0] (image) at (0,0) {\includegraphics[width=\textwidth,height=0.9\textheight,keepaspectratio]{./img/2015-01-19/03_hough_trafo.png}};
          \begin{scope}[x={(image.south east)},y={(image.north west)}]
            \draw[help lines,xstep=.1,ystep=.1] (0,0) grid (1,1);
            \foreach \x in {0,1,...,9} { \node [anchor=north] at (\x/10,0) {0.\x}; }
            \foreach \y in {0,1,...,9} { \node [anchor=east] at (0,\y/10) {0.\y}; }

            \node[draw, align=left] at (.2,.65) {distance};
            \draw[thick,|-|] (.326-.0487,.826-.026) -- (.5-.0487,.5-.026);

            \node[draw, align=left] at (.5,.87) {direction};
            \draw[ultra thick,->] (.326,.826) -- (.3936,.7);

            \node[draw, align=left] at (.76,.43) {desired ball position};
            % \draw[red,ultra thick,rounded corners] (0.5-.03,0.5-.03) rectangle (0.5+.03,0.5+.03);
          \end{scope}
      \end{tikzpicture}
    #+END_SRC
* [org-mode] PDF-Export-Variables                                  :noexport:
  [[https://github.com/vikasrawal/orgpaper/][orgpaper]] [[http://orgmode.org/manual/Export-settings.html][Org-Mode Export-Settings]] [[http://en.wikibooks.org/wiki/LaTeX/Print_version][nice LaTeX reference]]
** org-mode startup
#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: entitiespretty
*** Symbole
    [[http://orgmode.org/worg/org-symbols.html][verfügbare Symbols]]
** LaTeX Header
*** eigene Titlepage
    see [[http://orgmode.org/tmp/worg/org-tutorials/org-latex-export.html][11.2 Titles and Title Page Layout]]
,#+LATEX_HEADER: \input{mytitle}
*** Font
**** Arial
#+LATEX_HEADER: \renewcommand{\rmdefault}{phv} % Arial as Font!
**** libertine
,#+LATEX_HEADER: \usepackage{libertine}
**** garamond
,#+LaTeX_CLASS_OPTIONS: [garamond]
*** Zeilen-Abstand
,#+LATEX_HEADER: \usepackage{setspace}
,#+LATEX_HEADER: \onehalfspacing
*** language-specific [babel]
**** german
#+LANGUAGE:  de
#+LATEX_HEADER: \usepackage[ngerman]{babel}
**** neccessary
,#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage[T1]{fontenc} 
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
**** neo2 - uniinput
#+LATEX_HEADER: \usepackage{uniinput}
*** Links [hyperref]
**** remove boxes, use dark colored fonts to indicate links
,#+LATEX_HEADER: \usepackage{xcolor}
,#+LATEX_HEADER: \hypersetup{
,#+LATEX_HEADER:     colorlinks,
,#+LATEX_HEADER:     linkcolor={red!50!black},
,#+LATEX_HEADER:     citecolor={blue!50!black},
,#+LATEX_HEADER:     urlcolor={blue!80!black}
,#+LATEX_HEADER: }
**** green!
#+LATEX_HEADER: \usepackage{xcolor}% http://ctan.org/pkg/xcolor
#+LATEX_HEADER: \usepackage{hyperref}% http://ctan.org/pkg/hyperref
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:   colorlinks=true,
#+LATEX_HEADER:   linkcolor=blue!50!red,
#+LATEX_HEADER:   urlcolor=green!70!black
#+LATEX_HEADER: }
**** get rid of the red boxes drawn around links
,#+LATEX_HEADER: \usepackage{hyperref}  % 
,#+LATEX_HEADER: \hypersetup{
,#+LATEX_HEADER:     colorlinks,%
,#+LATEX_HEADER:     citecolor=black,%
,#+LATEX_HEADER:     filecolor=black,%
,#+LATEX_HEADER:     linkcolor=blue,%
,#+LATEX_HEADER:     urlcolor=black
,#+LATEX_HEADER: }
*** extra packages [graphicx]
,#+LATEX_HEADER: \usepackage{graphicx}
*** Seitenränder anpassen [geometry]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{left=1.2in,right=1.2in,top=1.2in,bottom=1.2in}

*** [todonotes]
,#+LaTeX_HEADER: \usepackage{todonotes}
**** vorher laden, falls mit optionen geladen werden soll
     - ifthen
     - xkeyval
     - xcolor
     - tikz
     - calc
     - graphicx
*** bibliograbhy [biblatex][csquotes]
,#+LATEX_HEADER: \usepackage["backend=bibtex, citestyle=authoryear-icomp, bibstyle=authoryear, hyperref=true, backref=true, maxcitenames=3, url=true, natbib=true"]{biblatex}
,#+LaTeX_HEADER: \usepackage[backend=biber]{biblatex}
,#+LaTeX_HEADER: \usepackage{csquotes}
,#+LaTeX_HEADER: \bibliography{./bibliography}
,#+LATEX_HEADER: \addbibresource{./bibliography}
,#+LaTeX_HEADER: \bibliography{references}
** Options
*** Inhaltsverzeichnis anpassen
#+OPTIONS: toc:2 H:3 num:2

*** Quotes
    Toggle smart quotes (org-export-with-smart-quotes).
#+OPTIONS: ':t

*** Tiefstellen
    Toggle TeX-like syntax for sub- and superscripts. If you write "^:{}",
    ‘a_{b}’ will be interpreted, but the simple ‘a_b’ will be left as it is
    (org-export-with-sub-superscripts).
#+OPTIONS: ^:nil

*** Tags exportieren?
#+OPTIONS: tags:n

** misc
#+TITLE: demo
#+DATE: \today
#+AUTHOR: Eduard Urfaust
#+EMAIL: Feder.Stahl@mode.org
