* [LaTeX]
** [Tikz]
*** Tikz picture - Grid - Draw on image
    [[http://tex.stackexchange.com/questions/9559/drawing-on-an-image-with-tikz][Stack Exchange]]
    #+BEGIN_SRC latex
      \begin{tikzpicture}
          \node[anchor=south west,inner sep=0] (image) at (0,0) {\includegraphics[width=\textwidth,height=0.9\textheight,keepaspectratio]{./img/2015-01-19/03_hough_trafo.png}};
          \begin{scope}[x={(image.south east)},y={(image.north west)}]
            \draw[help lines,xstep=.1,ystep=.1] (0,0) grid (1,1);
            \foreach \x in {0,1,...,9} { \node [anchor=north] at (\x/10,0) {0.\x}; }
            \foreach \y in {0,1,...,9} { \node [anchor=east] at (0,\y/10) {0.\y}; }

            \node[draw, align=left] at (.2,.65) {distance};
            \draw[thick,|-|] (.326-.0487,.826-.026) -- (.5-.0487,.5-.026);

            \node[draw, align=left] at (.5,.87) {direction};
            \draw[ultra thick,->] (.326,.826) -- (.3936,.7);

            \node[draw, align=left] at (.76,.43) {desired ball position};
            % \draw[red,ultra thick,rounded corners] (0.5-.03,0.5-.03) rectangle (0.5+.03,0.5+.03);
          \end{scope}
      \end{tikzpicture}
    #+END_SRC
*** Extract from here - many examples
    #+BEGIN_SRC latex
      \begin{tikzpicture}[>=latex,font=\sffamily,every node/.style={minimum width=1cm,minimum height=1.5em,outer sep=0pt,draw=black,fill=green!40,semithick}]

        \node at (0,0) (A) {valid};
        \node [anchor=west] at (A.east) (B) {valid};
        \node [anchor=west] at (B.east) (C) {valid};
        \node [anchor=west, fill=red!40] at (C.east) (D) {None};
        \node [anchor=west] at (D.east) (E) {valid};
        \node [anchor=west] at (E.east) (F) {valid};
        \node [anchor=west, fill=red!40] at (F.east) (G) {None};

        \uncover<7->{
          \node [anchor=south east] at (A.north west) (v_m) [above=1 and 0 of A] {$\begin{pmatrix} x_m \\ y_m \\ r_m \end{pmatrix}$};
          \draw [->, semithick] (v_m.south) -- (A.north);
        }
        % \pause

        \uncover<2->{

          \node (Filter0) [below=0.5 and 0 of D, fill=blue!40] {!= None};

          \node (J) [below=1.5 and 0 of B] {valid};
          \node [anchor=west] at (J.east) (K) {valid};
          \node [anchor=west] at (K.east) (L) {valid};
          \node [anchor=west] at (L.east) (M) {valid};
          \node [anchor=west] at (M.east) (N) {valid};

          \draw [decorate,decoration={brace,amplitude=10pt},rotate=90] (G.south east) -- (A.south west);

          \draw [decorate,decoration={brace,amplitude=10pt},rotate=90] (J.north west) -- (N.north east);
        }
        % \pause
        \uncover<3->{
          \draw [decorate,decoration={brace,amplitude=10pt},rotate=90] (N.south east) -- (J.south west);

          \node (Filter1) [below=0.5 and 0 of L, fill=yellow!40] {Enough valid tuples?};
        }
        % \pause
        \uncover<4->{
          \node (Average) [right=0 and 3 of Filter1, fill=blue!40] {Calculate averages};

          \draw [->, semithick] (Filter1.east) -- (Average.west);

          \node [anchor=south] at (Average.north) (Averaged) {$\begin{pmatrix} x_{avg} \\ y_{avg} \\ r_{avg} \end{pmatrix}$};

          \node (Update) [above=1 and 0 of Averaged, fill=blue!40, align=center] {Update\\Object Properties};

          \draw [->, semithick] (Averaged.north) -- (Update.south);
        }

        \uncover<4>{
          \node (explanation0) [draw=none, fill=none, right=0 and 2 of v_m, align=center] {These are actually used to draw\\the circles on the feedback camera-stream};
          \draw (explanation0.south) edge[->, thick, out=325, in=135] (Update.north);
        }

        \uncover<6->{
          \node (Comparison) [right=0 and 2 of v_m, fill=yellow!40] {
            \(
            \left\vert
              \begin{pmatrix}
                x_{avg} \\
                y_{avg} \\ 
              \end{pmatrix}
              -
              \begin{pmatrix}
                x_{cand} \\
                y_{cand} \\ 
              \end{pmatrix}
            \right\vert
            <
            {dist}_{max}
            \)
          };
        }
        % \pause
        \uncover<5->{
          \node (Candidate) [right=0 and 2 of Comparison.north east] {
            \(\begin{pmatrix}
              x_{cand} \\
              y_{cand} \\ 
            \end{pmatrix}\)
          };

          \uncover<5>{
            \node (Candidate_expl) [draw=none, fill=none, left=2 of Candidate, align=center] {A circle found in\\a new image from the stream};
            \draw (Candidate_expl.east) edge[->, thick, out=15, in=180-15] (Candidate.west);
          }

        }
        % \pause
        \uncover<6->{
          \draw [->, semithick] (Candidate.west) -- (Comparison.north east);
          \draw [->, semithick] (Update.north) |- (Comparison.south east);
        }

        \uncover<7->{
          \draw [->, semithick] (Comparison.west) -- (v_m.east);

          \draw (A.north) edge[out=45,in=135,->] (B.north);
          \draw (B.north) edge[out=45,in=135,->] (C.north);
          \draw (C.north) edge[out=45,in=135,->] (D.north);
          \draw (D.north) edge[out=45,in=135,->] (E.north);
          \draw (E.north) edge[out=45,in=135,->] (F.north);
          \draw (F.north) edge[out=60,in=120,->] (G.north);

          \draw (G.south west) edge[-, thick] (G.north east);
          \draw (G.north west) edge[-, thick] (G.south east);
        }

        \uncover<1>{
          \node (FIFO) [draw=none, fill=none, right=0 and 3 of v_m] {\Large{FIFO-Buffer}};
          \node (FIFO_expl) [draw=none, fill=none, below left = 0 and -2 of FIFO, align=center] {(One entry per\\processed image!)};
          \draw (FIFO.east) edge[->, thick, out=325, in=45] (G.north east);
        }

      \end{tikzpicture}

    #+END_SRC
* [org-mode] PDF-Export-Variables                                  :noexport:
  [[https://github.com/vikasrawal/orgpaper/][orgpaper]] [[http://orgmode.org/manual/Export-settings.html][Org-Mode Export-Settings]] [[http://en.wikibooks.org/wiki/LaTeX/Print_version][nice LaTeX reference]]
** org-mode startup
#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: entitiespretty
*** Symbole
    [[http://orgmode.org/worg/org-symbols.html][verfügbare Symbols]]
** LaTeX Header
*** eigene Titlepage
    see [[http://orgmode.org/tmp/worg/org-tutorials/org-latex-export.html][11.2 Titles and Title Page Layout]]
,#+LATEX_HEADER: \input{mytitle}
*** Font
**** Arial
#+LATEX_HEADER: \renewcommand{\rmdefault}{phv} % Arial as Font!
**** libertine
,#+LATEX_HEADER: \usepackage{libertine}
**** garamond
,#+LaTeX_CLASS_OPTIONS: [garamond]
*** Zeilen-Abstand
,#+LATEX_HEADER: \usepackage{setspace}
,#+LATEX_HEADER: \onehalfspacing
*** language-specific [babel]
**** german
#+LANGUAGE:  de
#+LATEX_HEADER: \usepackage[ngerman]{babel}
**** neccessary
,#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage[T1]{fontenc} 
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
**** neo2 - uniinput
#+LATEX_HEADER: \usepackage{uniinput}
*** Links [hyperref]
**** remove boxes, use dark colored fonts to indicate links
,#+LATEX_HEADER: \usepackage{xcolor}
,#+LATEX_HEADER: \hypersetup{
,#+LATEX_HEADER:     colorlinks,
,#+LATEX_HEADER:     linkcolor={red!50!black},
,#+LATEX_HEADER:     citecolor={blue!50!black},
,#+LATEX_HEADER:     urlcolor={blue!80!black}
,#+LATEX_HEADER: }
**** green!
#+LATEX_HEADER: \usepackage{xcolor}% http://ctan.org/pkg/xcolor
#+LATEX_HEADER: \usepackage{hyperref}% http://ctan.org/pkg/hyperref
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:   colorlinks=true,
#+LATEX_HEADER:   linkcolor=blue!50!red,
#+LATEX_HEADER:   urlcolor=green!70!black
#+LATEX_HEADER: }
**** get rid of the red boxes drawn around links
,#+LATEX_HEADER: \usepackage{hyperref}  % 
,#+LATEX_HEADER: \hypersetup{
,#+LATEX_HEADER:     colorlinks,%
,#+LATEX_HEADER:     citecolor=black,%
,#+LATEX_HEADER:     filecolor=black,%
,#+LATEX_HEADER:     linkcolor=blue,%
,#+LATEX_HEADER:     urlcolor=black
,#+LATEX_HEADER: }
*** extra packages [graphicx]
,#+LATEX_HEADER: \usepackage{graphicx}
*** Seitenränder anpassen [geometry]
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{left=1.2in,right=1.2in,top=1.2in,bottom=1.2in}

*** [todonotes]
,#+LaTeX_HEADER: \usepackage{todonotes}
**** vorher laden, falls mit optionen geladen werden soll
     - ifthen
     - xkeyval
     - xcolor
     - tikz
     - calc
     - graphicx
*** bibliograbhy [biblatex][csquotes]
,#+LATEX_HEADER: \usepackage["backend=bibtex, citestyle=authoryear-icomp, bibstyle=authoryear, hyperref=true, backref=true, maxcitenames=3, url=true, natbib=true"]{biblatex}
,#+LaTeX_HEADER: \usepackage[backend=biber]{biblatex}
,#+LaTeX_HEADER: \usepackage{csquotes}
,#+LaTeX_HEADER: \bibliography{./bibliography}
,#+LATEX_HEADER: \addbibresource{./bibliography}
,#+LaTeX_HEADER: \bibliography{references}
** Options
*** Inhaltsverzeichnis anpassen
#+OPTIONS: toc:2 H:3 num:2

*** Quotes
    Toggle smart quotes (org-export-with-smart-quotes).
#+OPTIONS: ':t

*** Tiefstellen
    Toggle TeX-like syntax for sub- and superscripts. If you write "^:{}",
    ‘a_{b}’ will be interpreted, but the simple ‘a_b’ will be left as it is
    (org-export-with-sub-superscripts).
#+OPTIONS: ^:nil

*** Tags exportieren?
#+OPTIONS: tags:n

** misc
#+TITLE: demo
#+DATE: \today
#+AUTHOR: Eduard Urfaust
#+EMAIL: Feder.Stahl@mode.org
